import type { NextPage } from 'next'
import Head from 'next/head'
// import type { SketchProps } from '@react-p5/core'
import styles from '../styles/Home.module.css'
// import dynamic from 'next/dynamic'
import { useState } from 'react'
import {createGrain} from "@react-p5/utils"
import type {Graphics} from 'p5'
import Sketch, {SketchProps} from "@react-p5/sketch"

// const Sketch = dynamic(() => import('@react-p5/core').then((mod) =>  mod.default
// ), {ssr: false});

let grain: Graphics

const Home: NextPage = () => {
  const [seed, setSeed] = useState<number>(0)

  const setup: SketchProps["setup"] = (p5, canvasParentRef) => {
    p5.createCanvas(800,800).parent(canvasParentRef)
    p5.background(255)
    setSeed(10)
    grain = createGrain(p5)
  }
  
  const draw: SketchProps["draw"] = p5 => {
    p5.randomSeed(seed)
    p5.background(255)
    p5.fill(255,0,0)
    const length = p5.random(200)

    Array.from({length}, () => {
      p5.ellipse(p5.random(p5.width), p5.random(p5.height), 20, 20)
    })

    p5.image(grain, 0, 0, p5.width, p5.height)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Nextjs @react-p5 Example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Sketch setup={setup} draw={draw} />
      </main>
    </div>
  )
}

export default Home
