import type { NextPage } from 'next'
import Head from 'next/head'
import type { SketchProps } from '../../../packages/core/dist'
import styles from '../styles/Home.module.css'
import dynamic from 'next/dynamic'
import { useState } from 'react'

const Sketch = dynamic(() => import('../../../packages/core/dist').then((mod) =>  mod.default
), {ssr: false});


const Home: NextPage = () => {
  const [seed, setSeed] = useState<number>(0)

  const setup: SketchProps["setup"] = (p5, canvasParentRef) => {
    p5.createCanvas(800,800).parent(canvasParentRef)
    p5.background(255)
    setSeed(10)
  }
  
  const draw: SketchProps["draw"] = p5 => {
    p5.randomSeed(seed)
    p5.background(255)
    p5.fill(255,0,0)
    const length = p5.random(200)

    Array.from({length}, () => {
      p5.ellipse(p5.random(p5.width), p5.random(p5.height), 20, 20)
    })
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <Sketch setup={setup} draw={draw} />
      </main>
    </div>
  )
}

export default Home
